/smart_radar:
  ros__parameters:
      adapters:
        adapter_0:
          hw_dev_id: 2
          hw_iface_name: "br0"  # "enp5s0"
          hw_type: eth
          port: 55555
      master_data_serial_type: port_based
      master_inst_serial_type: port_based

    # # The client_id to be set in smart_access_config.json, must be a unique integer.
    #   master_client_id: 1000
    #   # This sets the dev_id in the hw_inventory.json
    #   hw_dev_id: 2
    #   # This sets the port in the hw_inventory.json
    #   hw_port: 55555
    #   # This sets the iface_name in the hw_inventory.json
    #   hw_iface_name: "eth0"
      # An array of sensors to subscribe to.
      sensors:
          # As many as 10 sensors all named as "sensor_<number>" in increasing order of numbers,
          # e.g., sensor_0, sensor_1, etc. The list must start with sensor_0.
          sensor_0:
            # The link of the sensor either 'can' or 'eth'
            link_type: "eth"
            # The publisher type of the sensor
            pub_type: "target"
            # The model of the connected sensor.
            model: "umrr96_v1_2_2"
            # Adapter id to which sensor is connected
            dev_id: 2
            # The client_id of the sensor/source, must be a unique integer.
            id: 100
            # The ip address of the sensor or of the source acting as a sensor.
            ip: "192.168.1.6"
            # The port to be used.
            port: 55555
            # The frame_id to be set to the published messages.
            frame_id: "pass_rear_side"
            # Specify the history size.
            history_size: 10
            inst_type: "port_based"
            data_type: "port_based"
            # The interface name of the sensor
            uifname: "umrr96_t153_automotive"
            # The major version of the interface
            uifmajorv: 1
            # The minor version of the interface
            uifminorv: 2
            # The pathc version of the interface
            uifpatchv: 2

          sensor_1:
            # The link of the sensor either 'can' or 'eth'
            link_type: "eth"
            # The publisher type of the sensor
            pub_type: "target"
            # The model of the connected sensor.
            model: "umrr96_v1_2_2"
            # Adapter id to which sensor is connected
            dev_id: 2
            # The client_id of the sensor/source, must be a unique integer.
            id: 200
            # The ip address of the sensor or of the source acting as a sensor.
            ip: "192.168.1.7"
            # The port to be used.
            port: 55555
            # The frame_id to be set to the published messages.
            frame_id: "pass_rear"
            # Specify the history size.
            history_size: 10
            inst_type: "port_based"
            data_type: "port_based"
            # The interface name of the sensor
            uifname: "umrr96_t153_automotive"
            # The major version of the interface
            uifmajorv: 1
            # The minor version of the interface
            uifminorv: 2
            # The pathc version of the interface
            uifpatchv: 2

          sensor_2:
            # The link of the sensor either 'can' or 'eth'
            link_type: "eth"
            # The publisher type of the sensor
            pub_type: "target"
            # The model of the connected sensor.
            model: "umrr96_v1_2_2"
            # Adapter id to which sensor is connected
            dev_id: 2
            # The client_id of the sensor/source, must be a unique integer.
            id: 300
            # The ip address of the sensor or of the source acting as a sensor.
            ip: "192.168.1.4"
            # The port to be used.
            port: 55555
            # The frame_id to be set to the published messages.
            frame_id: "pass_front"
            # Specify the history size.
            history_size: 10
            inst_type: "port_based"
            data_type: "port_based"
            # The interface name of the sensor
            uifname: "umrr96_t153_automotive"
            # The major version of the interface
            uifmajorv: 1
            # The minor version of the interface
            uifminorv: 2
            # The pathc version of the interface
            uifpatchv: 2


          sensor_3:
            # The link of the sensor either 'can' or 'eth'
            link_type: "eth"
            # The publisher type of the sensor
            pub_type: "target"
            # The model of the connected sensor.
            model: "umrr96_v1_2_2"
            # Adapter id to which sensor is connected
            dev_id: 2
            # The client_id of the sensor/source, must be a unique integer.
            id: 400
            # The ip address of the sensor or of the source acting as a sensor.
            ip: "192.168.1.5"
            # The port to be used.
            port: 55555
            # The frame_id to be set to the published messages.
            frame_id: "front_pass_side"
            # Specify the history size.
            history_size: 10
            inst_type: "port_based"
            data_type: "port_based"
            # The interface name of the sensor
            uifname: "umrr96_t153_automotive"
            # The major version of the interface
            uifmajorv: 1
            # The minor version of the interface
            uifminorv: 2
            # The pathc version of the interface
            uifpatchv: 2
          
          
          sensor_4:
            # The link of the sensor either 'can' or 'eth'
            link_type: "eth"
            # The publisher type of the sensor
            pub_type: "target"
            # The model of the connected sensor.
            model: "umrr96_v1_2_2"
            # Adapter id to which sensor is connected
            dev_id: 2
            # The client_id of the sensor/source, must be a unique integer.
            id: 500
            # The ip address of the sensor or of the source acting as a sensor.
            ip: "192.168.1.8"
            # The port to be used.
            port: 55555
            # The frame_id to be set to the published messages.
            frame_id: "driver_rear"
            # Specify the history size.
            history_size: 10
            inst_type: "port_based"
            data_type: "port_based"
            # The interface name of the sensor
            uifname: "umrr96_t153_automotive"
            # The major version of the interface
            uifmajorv: 1
            # The minor version of the interface
            uifminorv: 2
            # The pathc version of the interface
            uifpatchv: 2


          sensor_5:
            # The link of the sensor either 'can' or 'eth'
            link_type: "eth"
            # The publisher type of the sensor
            pub_type: "target"
            # The model of the connected sensor.
            model: "umrr96_v1_2_2"
            # Adapter id to which sensor is connected
            dev_id: 2
            # The client_id of the sensor/source, must be a unique integer.
            id: 600
            # The ip address of the sensor or of the source acting as a sensor.
            ip: "192.168.1.9"
            # The port to be used.
            port: 55555
            # The frame_id to be set to the published messages.
            frame_id: "driver_rear_side"
            # Specify the history size.
            history_size: 10
            inst_type: "port_based"
            data_type: "port_based"
            # The interface name of the sensor
            uifname: "umrr96_t153_automotive"
            # The major version of the interface
            uifmajorv: 1
            # The minor version of the interface
            uifminorv: 2
            # The pathc version of the interface
            uifpatchv: 2


          sensor_6:
            # The link of the sensor either 'can' or 'eth'
            link_type: "eth"
            # The publisher type of the sensor
            pub_type: "target"
            # The model of the connected sensor.
            model: "umrr96_v1_2_2"
            # Adapter id to which sensor is connected
            dev_id: 2
            # The client_id of the sensor/source, must be a unique integer.
            id: 700
            # The ip address of the sensor or of the source acting as a sensor.
            ip: "192.168.1.10"
            # The port to be used.
            port: 55555
            # The frame_id to be set to the published messages.
            frame_id: "driver_front_side"
            # Specify the history size.
            history_size: 10
            inst_type: "port_based"
            data_type: "port_based"
            # The interface name of the sensor
            uifname: "umrr96_t153_automotive"
            # The major version of the interface
            uifmajorv: 1
            # The minor version of the interface
            uifminorv: 2
            # The pathc version of the interface
            uifpatchv: 2

          sensor_7:
            # The link of the sensor either 'can' or 'eth'
            link_type: "eth"
            # The publisher type of the sensor
            pub_type: "target"
            # The model of the connected sensor.
            model: "umrr96_v1_2_2"
            # Adapter id to which sensor is connected
            dev_id: 2
            # The client_id of the sensor/source, must be a unique integer.
            id: 800
            # The ip address of the sensor or of the source acting as a sensor.
            ip: "192.168.1.11"
            # The port to be used.
            port: 55555
            # The frame_id to be set to the published messages.
            frame_id: "driver_front"
            # Specify the history size.
            history_size: 10
            inst_type: "port_based"
            data_type: "port_based"
            # The interface name of the sensor
            uifname: "umrr96_t153_automotive"
            # The major version of the interface
            uifmajorv: 1
            # The minor version of the interface
            uifminorv: 2
            # The pathc version of the interface
            uifpatchv: 2


          sensor_8:
            # The link of the sensor either 'can' or 'eth'
            link_type: "eth"
            # The publisher type of the sensor
            pub_type: "target"
            # The model of the connected sensor.
            model: "umrr96_v1_2_2"
            # Adapter id to which sensor is connected
            dev_id: 2
            # The client_id of the sensor/source, must be a unique integer.
            id: 900
            # The ip address of the sensor or of the source acting as a sensor.
            ip: "192.168.1.12"
            # The port to be used.
            port: 55555
            # The frame_id to be set to the published messages.
            frame_id: "front_center"
            # Specify the history size.
            history_size: 10
            inst_type: "port_based"
            data_type: "port_based"
            # The interface name of the sensor
            uifname: "umrr96_t153_automotive"
            # The major version of the interface
            uifmajorv: 1
            # The minor version of the interface
            uifminorv: 2
            # The pathc version of the interface
            uifpatchv: 2
